name: Build APK

on:
  push:
    paths-ignore:
      - '**.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Get short commit SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Grant execution permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew build

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: No Internal Problem-CI-${{ env.SHORT_SHA }}-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: No Internal Problem-CI-${{ env.SHORT_SHA }}-release-unsigned.apk
          path: app/build/outputs/apk/release/app-release.apk
